services:
  mongodb:
    container_name: mongo
    # image: mongo:latest
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: